=== pombreda/pgreloaded/doc/src/api.dtd
<!DOCTYPE module [
<!ELEMENT module
          (show?, alias?, short, desc, example?,
          (data | func | class)*, include*)
          >
<!ATTLIST module name CDATA #REQUIRED>

<!ELEMENT show (0 | 1) "1">
<!ELEMENT alias (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT short (#PCDATA)>

<!ELEMENT data (#PCDATA)>
<!ATTLIST data name CDATA #REQUIRED>

<!ELEMENT call (#PCDATA)>
<!ELEMENT include (#PCDATA)>

<!ELEMENT func (call, desc, example?)>
<!ATTLIST func name CDATA #REQUIRED>

<!ELEMENT class (constructor, desc, example?, (attr | method)*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT constructor (#PCDATA)>

<!ELEMENT attr (desc, example?)>
<!ATTLIST attr name CDATA #REQUIRED>

<!ELEMENT method (call, desc, example*)>
<!ATTLIST method name CDATA #REQUIRED>

]>

=== pombreda/pgreloaded/doc/src/sdlimage.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.image">
  <short>SDL image I/O wrapper module</short>
  <desc>SDL image I/O wrapper module</desc>

  <func name="load_bmp">
    <call>load_bmp (file) -> Surface</call>
    <desc>
      Loads a BMP file and creates a :class:`pygame2.sdl.video.Surface` from it.
    
      Loads a BMP file and creates a :class:`pygame2.sdl.video.Surface` from it.
      The *file* argument can be either a file object or the filename.

      .. note::
      
        The file object *must* support binary read and write
        access. This is especially important for Python 3.x users.

    </desc>
  </func>
  <func name="save_bmp">
    <call>save_bmp (surface, file) -> None</call>
    <desc>Saves a surface to a bitmap file.

      Saves a :class:`pygame2.sdl.video.Surface` to the specified file, where
      *file* can be a filename or file object.

      .. note::
      
        The file object *must* support binary read and write
        access. This is especially important for Python 3.x users.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlaudio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.audio">
  <short>SDL audio subsystem wrapper</short>
  <desc>Pygame SDL audio subsystem wrapper module.

    .. note::

      Do not use :mod:`pygame2.sdlmixer` and :mod:`pygame2.sdl.audio` at the
      same time. As they both deal with audio hardware access, this can lead
      to problems and weird behaviour.
  </desc>

  <func name="init">
    <call>init () -> None</call>
    <desc>
      Initializes the audio subsystem of the SDL library.
    </desc>
  </func>
  <func name="quit">
    <call>quit () -> None</call>
    <desc>
      Shuts down the audio subsystem of the SDL library.

      After calling this function, you should not invoke any class,
      method or function related to the audio subsystem as they are
      likely to fail or might give unpredictable results.
    </desc>
  </func>
  <func name="was_init">
    <call>was_init () -> bool</call>
    <desc>
      Returns, whether the audio subsystem of the SDL library is initialized.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/mathbase.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.math.base">
  <show>0</show>
  <alias>pygame2.math</alias>
  <short>Vector math module for Pygame2</short>
  <desc>
    Vector math module for Pygame2
  </desc>
  <func name="vector_from_polar">
    <call>vector_from_polar (p1, p2) -> Vector2</call>
    <desc>
      Creates a 2D vector from the passed polar coordinates.
    </desc>
  </func>
  <func name="vector_from_spherical">
    <call>vector_from_spherical (p1, p2, p3) -> Vector2</call>
    <desc>
      Creates a 3D vector from the passed spherical coordinates.
    </desc>
  </func>

  <class name="Vector">
    <constructor>Vector (elements) -> Vector</constructor>
    <desc>Creates a new Vector with the specified elements or dimension.
    
      Creates a new n-dimensional Vector. *elements* can be either a sequence of
      numbers representing the values for each dimension or a positive integer
      to create an empty vector with *elements* dimensions.
    </desc>
    <example>
      from pygame2.math import Vector
      
      # Create a 3D vector with x=1, y=2 and z=3
      v1 = Vector ([1, 2, 3])
      
      # Create a vector with 15 dimensions, where each component is set to 0.
      v2 = Vector (15)
    </example>
    <attr name="dimension">
      <desc>Gets the dimensions of the :class:`Vector`.</desc>
    </attr>
    <attr name="length">
      <desc>Gets the length of the :class:`Vector`.</desc>
    </attr>
    <attr name="length_squared">
      <desc>Gets the length of the :class:`Vector`.</desc>
    </attr>
    <attr name="epsilon">
      <desc>Gets or sets the exactness delta of the :class:`Vector`.
      
      epsilon represents a small fractional value to come around
      rounding issues on floating point calculations. It is usually used
      to soothe rounding differences and thus to allow the system to
      return an appropriate state, with a small tradeoff for the
      exactness.

      **Example:** ::

        (0.0000000000001 - 0.0000000000009) == 0.0

      Given that epsilon is large enough, the above calculation will be
      true. To get over rounding issues on vector operations with small
      fractional parts or to make them more exact, the concrete epsilon
      value can be freely adjusted.
      </desc>
    </attr>
    <attr name="elements">
      <desc>Gets or sets the elements of the :class:`Vector`.
    
      This will only set a maximum of :attr:`dimension` values.
      </desc>
    </attr>
    <attr name="normalized">
      <desc>Gets whether the :class:`Vector` is normalized.</desc>
    </attr>
    <method name="normalize">
      <call>normalize () -> Vector</call>
      <desc>Creates a normalized representation of this Vector.</desc>
    </method>
    <method name="normalize_ip">
      <call>normalize_ip () -> None</call>
      <desc>Normalizes the Vector in place.</desc>
    </method>
    <method name="slerp">
      <call>slerp () -> Vector</call>
      <desc></desc>
    </method>
    <method name="lerp">
      <call>lerp () -> Vector</call>
      <desc></desc>
    </method>
    <method name="dot">
      <call>dot (v) -> float</call>
      <desc>Calculates the dot product of the Vector and the passed argument.
      </desc>
    </method>
    <method name="scale_to">
      <call>scale_to (length) -> Vector</call>
      <desc>Scales the Vector to match the passed length.</desc>
    </method>
    <method name="reflect">
      <call>reflect () -> Vector</call>
      <desc>Creates a reflected representation of the Vector.</desc>
    </method>
    <method name="reflect_ip">
      <call>reflect_ip () -> None</call>
      <desc>Reflects the Vector in place.</desc>
    </method>
    <method name="distance">
      <call>distance (v) -> float</call>
      <desc>Calculates the distance between two vectors.</desc>
    </method>
    <method name="distance_squared">
      <call>distance_squared () -> None</call>
      <desc>Calculates the squared distance between two vectors.</desc>
    </method>
  </class>
  
  <class name="Vector2">
    <constructor>Vector2 () -> Vector2</constructor>
    <desc>Creates a new Vector2.
    
      A simple 2D vector containing only two elements.
    </desc>
    <attr name="dimension">
      <desc>Gets the dimensions of the :class:`Vector2`.</desc>
    </attr>
    <attr name="elements">
      <desc>Gets or sets the elements of the :class:`Vector2`.
    
        This will only set a maximum of two values.
      </desc>
    </attr>
    <attr name="x">
      <desc>Gets or sets first element of the :class:`Vector2`.</desc>
    </attr>
    <attr name="y">
      <desc>Gets or sets second element of the :class:`Vector2`.</desc>
    </attr>
    <method name="rotate">
      <call>rotate (angle) -> Vector2</call>
      <desc>Rotates the Vector2 by the passed degrees.</desc>
    </method>
    <method name="rotate_ip">
      <call>rotate_ip (angle) -> Vector2</call>
      <desc>Rotates the Vector2 by the passed degrees in place.</desc>
    </method>
    <method name="as_polar">
      <call>as_polar () -> float, float</call>
      <desc>Gets the polar coordinate representation of the Vector2.</desc>
    </method>
    <method name="angle_to">
      <call>angle_to (v) -> float</call>
      <desc>Calculates the angle (in degrees) between two Vector2 objects.</desc>
    </method>
    <method name="cross">
      <call>cross (v) -> Vector2</call>
      <desc>Creates the cross product of the two Vector2 objects.</desc>
    </method>
  </class>

  <class name="Vector3">
    <constructor>Vector3 () -> Vector3</constructor>
    <desc>Creates a new Vector3.
    
      A simple 3D vector containing only three elements.
    </desc>
    <attr name="dimension">
      <desc>Gets the dimensions of the :class:`Vector3`.</desc>
    </attr>
    <attr name="elements">
      <desc>Gets or sets the elements of the :class:`Vector3`.
    
        This will only set a maximum of three values.
      </desc>
    </attr>
    <attr name="x">
      <desc>Gets or sets first element of the :class:`Vector3`.</desc>
    </attr>
    <attr name="y">
      <desc>Gets or sets second element of the :class:`Vector3`.</desc>
    </attr>
    <attr name="z">
      <desc>Gets or sets third element of the :class:`Vector3`.</desc>
    </attr>
    <method name="rotate_x">
      <call>rotate_x (angle) -> Vector3</call>
      <desc>Rotates the Vector3 by the passed degrees around the x-axis.</desc>
    </method>
    <method name="rotate_x_ip">
      <call>rotate_x_ip (angle) -> None</call>
      <desc>Rotates the Vector3 by the passed degrees in place around the x-axis.
      </desc>
    </method>
    <method name="rotate_y">
      <call>rotate_y (angle) -> Vector3</call>
      <desc>Rotates the Vector3 by the passed degrees around the y-axis.</desc>
    </method>
    <method name="rotate_y_ip">
      <call>rotate_y_ip (angle) -> None</call>
      <desc>Rotates the Vector3 by the passed degrees in place around the y-axis.</desc>
    </method>
    <method name="rotate_z">
      <call>rotate_z (angle) -> Vector3</call>
      <desc>Rotates the Vector3 by the passed degrees around the z-axis.</desc>
    </method>
    <method name="rotate_z_ip">
      <call>rotate_z_ip (angle) -> None</call>
      <desc>Rotates the Vector3 by the passed degrees in place around the z-axis.</desc>
    </method>
    <method name="rotate">
      <call>rotate (angle, axis) -> Vector3</call>
      <desc>Rotates the Vector3 by the passed degrees around the passed axis vector.
      </desc>
    </method>
    <method name="rotate_ip">
      <call>rotate_ip (angle, axis) -> Vector3</call>
      <desc>Rotates the Vector3 by the passed degrees in place around the passed axis vector.
      </desc>
    </method>
    <method name="angle_to">
      <call>angle_to (v) -> float</call>
      <desc>Calculates the angle between two vectors in degrees</desc>
    </method>
    <method name="cross">
      <call>cross (v) -> Vector3</call>
      <desc>Calculates the cross product between the two Vector3 instances.</desc>
    </method>
    <method name="as_spherical">
      <call>as_spherical () -> float, float, float</call>
      <desc>Gets the sperhical coordinate representation of the Vector3.</desc>
    </method>
  </class>

</module>

=== pombreda/pgreloaded/doc/src/sdlgfxrotozoom.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlgfx.rotozoom">
  <short>SDL_gfx rotozoom wrapper module</short>
  <desc>SDL_gfx rotozoom wrapper module</desc>

  <func name="rotate_90">
    <call>rotate_90 (surface, times) -> Surface
    </call>
    <desc>Rotates a surface clockwise by 90 degrees.
      
      Rotates the passed *surface* clockwise by 90 degrees and returns a new
      :class:`pygame2.sdl.video.Surface` with the rotated result.
      *times* denotes the amount of rotations to perform.
    </desc>
  </func>
  <func name="rotozoom">
    <call>rotozoom (surface, angle, zoom[, smooth]) -> Surface</call>
    <desc>Rotates and zooms a surface.
    
      Rotates and zooms a *surface* at the same time and returns a new
      :class:`pygame2.sdl.video.Surface` with the result. *angle* is the
      rotation angle in degrees, *zoom* the zoom factor. The optional
      *smooth* argument is used for smoothing the edges and pixels of
      the returned surface.
    </desc>
  </func>
  <func name="rotozoom_size">
    <call>rotozoom_size (width, height, angle, zoom) -> int, int
    rotozoom_size (size, angle, zoom) -> int, int
    rotozoom_size (surface, angle, zoom) -> int, int
    </call>
    <desc>Calculates the resulting surface size for a rotozoom operation.
      
      Calculates the size of the resulting surface, if a rotozoom operation
      takes place on a specific :class:`pygame2.sdl.video.Surface`.
    </desc>
  </func>
  <func name="rotozoom_size_xy">
    <call>rotozoom_size_xy (width, height, angle, zoomx, zoomy) -> int, int
    rotozoom_size_xy (size, angle, zoomx, zoomy) -> int, int
    rotozoom_size_xy (surface, angle, zoomx, zoomy) -> int, int
    </call>
    <desc>Calculates the resulting surface size for a rotozoom operation.
      
      Calculates the size of the resulting surface, if a rotozoom operation
      takes place on a specific :class:`pygame2.sdl.video.Surface`.
    </desc>
  </func>
  <func name="rotozoom_xy">
    <call>rotozoom_xy (surface, angle, zoomx, zoomy[, smooth]) -> Surface</call>
    <desc>Rotates and zooms a surface with different scaling factors for the x- and y- axes.
    
      Rotates and zooms a *surface* at the same time and returns a new
      :class:`pygame2.sdl.video.Surface` with the result. *angle* is the
      rotation angle in degrees, *zoomx* and *zoomy* the zoom factors
      for the x- and y-axis. The optional *smooth* argument is used for
      smoothing the edges and pixels of the returned surface.
    </desc>
  </func>
  <func name="shrink">
    <call>zoom (surface, shrinkx, shrinky) -> Surface
    </call>
    <desc>Shrinks a surface.
      
      Shrinks a *surface* and returns a new
      :class:`pygame2.sdl.video.Surface` with the result. *shrinkx* and
      *shrinky* are the shrink factors for the x- and y-axis.
    </desc>
  </func>
  <func name="zoom">
    <call>zoom (surface, zoomx, zoomy[, smooth]) -> Surface</call>
    <desc>Zooms a surface.
    
      Zooms a *surface* and returns a new
      :class:`pygame2.sdl.video.Surface` with the result. *zoomx* and
      *zoomy* are the zoom factors for the x- and y-axis. The optional
      *smooth* argument is used for smoothing the edges and pixels of
      the returned surface.
    </desc>
  </func>
  <func name="zoom_size">
    <call>zoom_size (width, height, angle, zoom) -> int, int
          zoom_size (surface, angle, zoom) -> int, int
    </call>
    <desc>Calculates the resulting surface size for a zoom operation.
      
      Calculates the size of the resulting surface, if a zoom operation
      takes place on a specific :class:`pygame2.sdl.video.Surface`.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlwm.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.wm">
  <short>SDL window manager wrapper module</short>
  <desc>Pygame SDL window manager wrapper module.</desc>

  <func name="get_caption">
    <call>get_caption () -> str, str</call>
    <desc>Gets the caption of the current SDL window.
    
      Gets the title-bar caption and icon name (if any) of the display
      window. If not set, any of the values might be None.
    </desc>
  </func>
  <func name="get_info">
    <call>get_info () -> dict</call>
    <desc>
      Gets operating system and window manager specific information about the
      current SDL window.
    </desc>
  </func>
  <func name="grab_input">
    <call>grab_input (mode) -> int</call>
    <desc>
      Advices the window manager to let the window grab the mouse and keyboard
      input focus (or release it). The function returns the previously set mode.
    </desc>
  </func>
  <func name="iconify_window">
    <call>iconify_window () -> bool</call>
    <desc>
      Advices the window manager to iconify the window and returns, whether the
      operation was successful or not.
    </desc>
  </func>
  <func name="set_caption">
    <call>set_caption (title[, iconname]) -> None</call>
    <desc>Sets the caption of the current SDL window.
    
      Sets the title-bar caption and optional icon name (or description)
      of the display window.
    </desc>
  </func>
  <func name="set_icon">
    <call>set_icon (surface[, mask]) -> None</call>
    <desc>
      Sets the window manager icon to be used by the window.
    </desc>
  </func>
  <func name="toggle_fullscreen">
    <call>toggle_fullscreen (bool) -> bool</call>
    <desc>
      Tries to toggle the fullscreen mode for the SDL window and
      returns, whether the operation was successful or not.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlgfxprimitives.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlgfx.primitives">
  <short>SDL_gfx primitives drawing module</short>
  <desc>SDL_gfx primitives drawing module</desc>

  <func name="aacircle">
    <call>aacircle (surface, x, y, radius, color) -> None
    aacircle (surface, point, radius, color) -> None</call>
    <desc>Draws an anti-aliased circular shape on a surface.
    
      Draws a anti-aliased circular shape on a *surface* with a fixed line
      width of 1px. The *x*, *y* point denotes the center of the circle.
    </desc>
  </func>
  <func name="aaellipse">
    <call>aaellipse (surface, x, y, rx, ry, color) -> None
    aaellipse (surface, point, radius, color) -> None</call>
    <desc>Draws an anti-aliased elliptical shape on a surface.
    
      Draws an anti-aliased elliptical shape on a *surface* with a fixed
      line width of 1px. The *x*, *y* tuple denotes the center of the
      ellipse, *rx*, *ry* the radius for the x- and y-axis.
    </desc>
  </func>
  <func name="aaline">
    <call>aaline (surface, x1, y1, x2, y2, color) -> None
    aaline (surface, point1, point2, color) -> None</call>
    <desc>Draws an anti-aliased line on a surface.
    
      Draws an anti-aliased line on a *surface* with a fixed width of
      1px. *x1*, *y1* and *x2*, *y2* denote the start and end position
      of the line.
    </desc>
  </func>
  <func name="aapolygon">
    <call>aapolygon (surface, (point1, point2, ...), color) -> None</call>
    <desc>Draws an anti-aliased polygonal shape on a surface.
    
      Draws an anti-aliased polygonal shape on a *surface* with an fixed line
      width of 1px.
    </desc>
  </func>
  <func name="aatrigon">
    <call>aatrigon (surface, x1, y1, x2, y2, x3, y3, color) -> None
    aatrigon (surface, point1, point2, point3, color) -> None</call>
    <desc>Draws an anti-aliased triangular shape on a surface.
      
      Draws an anti-aliased triangular shape on a *surface* with an fixed
      line width of 1px. The three *x*, *y* points denote the edges of
      the triangle.
    </desc>
  </func>
  <func name="arc">
    <call>arc (surface, x, y, radius, startangle, stopangle, color) -> None
    arc (surface, point, radius, startangle, stopangle, color) -> None</call>
    <desc>Draws an elliptical arc on a surface.
    
      Draws an elliptical arc on a *surface*. The *startangle* and
      *stopangle* arguments are the initial and final angle in degrees.
    </desc>
  </func>
  <func name="bezier">
    <call>bezier (surface, (point1, point2, ...), steps, color) -> None
    </call>
    <desc>Draws a bezier curve on a surface.
      
      Draws a bezier curve through the given points on a *surface*. *steps*
      denotes the amount of steps to perform for interpolating the curve.
    </desc>
  </func>
  <func name="box">
    <call>box (surface, rect, color) -> None</call>
    <desc>Draws a filled rectangular shape on a surface.
      
      Draws a filled rectangular shape on a surface.
    </desc>
  </func>
  <func name="circle">
    <call>circle (surface, x, y, radius, color) -> None
    circle (surface, point, radius, color) -> None</call>
    <desc>Draws a circular shape on a surface.
    
      Draws a circular shape on a *surface* with a fixed line width of
      1px. The *x*, *y* point denotes the center of the circle.
    </desc>
  </func>
  <func name="ellipse">
    <call>ellipse (surface, x, y, rx, ry, color) -> None
    ellipse (surface, point, radius, color) -> None</call>
    <desc>Draws an elliptical shape on a surface.
    
      Draws an elliptical shape on a *surface* with a fixed line width of
      1px.  The *x*, *y* point denotes the center of the ellipse, *rx*,
      *ry* the radius for the x- and y-axis.
    </desc>
  </func>
  <func name="filled_circle">
    <call>filled_circle (surface, x, y, radius, color) -> None
    filled_circle (surface, point, radius, color) -> None</call>
    <desc>Draws a filled circular shape on a surface.
    
      Draws a filled circular shape on a *surface*. The *x*, *y* point
      denotes the center of the circle.
    </desc>
  </func>
  <func name="filled_ellipse">
    <call>filled_ellipse (surface, x, y, rx, ry, color) -> None
    filled_ellipse (surface, point, radius, color) -> None</call>
    <desc>Draws a filled elliptical shape on a surface.
    
      Draws a filled elliptical shape on a *surface*. The *x*, *y* point
      denotes the center of the ellipse, *rx*, *ry* the radius for the
      x- and y-axis.
    </desc>
  </func>
  <func name="filled_pie">
    <call>filled_pie (surface, x, y, r, startangle, stopangle, color) -> None
    filled_pie (surface, point, r, startangle, stopangle, color) -> None
    </call>
    <desc>Draws a filled pie-like shape on a surface.
    
      Draws a filled pie-like shape on a *surface*. The *x*, *y* point
      denotes the center of the pie segment, *startangle* and
      *stopangle* the initial and final angle in degrees.
    </desc>
  </func>
  <func name="filled_polygon">
    <call>filled_polygon (surface, (point1, point2, ...), color) -> None
    </call>
    <desc>Draws a filled polygonal shape on a surface.
    
      Draws a filled polygonal shape on a *surface*.
    </desc>
  </func>
  <func name="filled_trigon">
    <call>filled_trigon (surface, x1, y1, x2, y2, x3, y3, color) -> None
    filled_trigon (surface, point1, point2, point3, color) -> None</call>
    <desc>Draws a filled triangular shape on a surface.
    
      Draws a filled triangular shape on a *surface*. The three *x*, *y*
      points denote the edges of the triangle.
    </desc>
  </func>
  <func name="hline">
    <call>hline (surface, x1, x2, y, color) -> None</call>
    <desc>Draws a horizontal line on a surface.
    
      Draws a horizontal line on a *surface* with the fixed width of 1 px.
      *x1* and *x2* denote the start and end position on the x-axis, *y*
      the vertical position of the line on the y-axis.
    </desc>
  </func>
  <func name="line">
    <call>line (surface, x1, y1, x2, y2, color) -> None
    line (surface, point1, point2, color) -> None</call>
    <desc>Draws a line on a surface.
    
      Draws a line on a *surface* with a fixed width of 1px. *x1*, *y1*
      and *x2*, *y2* denote the start and end position of the line.
    </desc>
  </func>
  <func name="pie">
    <call>pie (surface, x, y, r, startangle, stopangle, color) -> None
    pie (surface, point, r, startangle, stopangle, color) -> None</call>
    <desc>Draws a pie-like shape on a surface.
    
      Draws a pie-like shape on a *surface* with a fixed width of 1px. The
      *x*, *y* point denotes the center of the pie segment, *startangle*
      and *stopangle* the initial and final angle in degrees.
    </desc>
  </func>
  <func name="pixel">
    <call>pixel (surface, x, y, color) -> None
    pixel (surface, point, color) -> None</call>
    <desc>Draws a single pixel on a surface.
      
      Draws a single pixel on a *surface*.
    </desc>
  </func>
  <func name="polygon">
    <call>polygon (surface, ((x1, y1), (x2, y2), ...), color) -> None</call>
    <desc>Draws a polygonal shape on a surface.
    
      Draws a polygonal shape on a *surface*.
    </desc>
  </func>
  <func name="rectangle">
    <call>rectangle (surface, rect, color) -> None</call>
    <desc>Draws a rectangular shape on a surface.
      
      Draws a rectangular shape on a *surface*.
    </desc>
  </func>
  <func name="textured_polygon">
    <call>textured_polygon (surface, (point1, point2, ...), texture, tx, ty) -> None
    textured_polygon (surface, (point1, point2, ...), texture, tpoint) -> None
    </call>
    <desc>Draws a textured polygonal shape on a surface.
    
      Draws a textured polygonal shape on a *surface*. *texture* is a
      :class:`pygame2.sdl.video.Surface` to be used for filling the shape,
      *tx*, *ty* are the offset of the texture relative to the screen.
    </desc>
  </func>
  <func name="trigon">
    <call>trigon (surface, x1, y1, x2, y2, x3, y3, color) -> None
    trigon (surface, point1, point2, point3, color) -> None</call>
    <desc>Draws a triangular shape on a surface.
    
      Draws a filled triangular shape on a *surface* with a fixed line
      width of 1px. The three *x*, *y* points denote the edges of the
      triangle.
    </desc>
  </func>
  <func name="vline">
    <call>vline (surface, x, y1, y2, color) -> None</call>
    <desc>Draws a vertical line on a surface.
    
      Draws a vertical line on a *surface* with a fixed width of 1px. *y1*
      and *y2* denote the start and end position on the y-axis, *x* the
      horizontal position of the line on the x-axis.
    </desc>
  </func>
</module>
