=== pombreda/pgreloaded/doc/src/api.dtd
<!DOCTYPE module [
<!ELEMENT module
          (show?, alias?, short, desc, example?,
          (data | func | class)*, include*)
          >
<!ATTLIST module name CDATA #REQUIRED>

<!ELEMENT show (0 | 1) "1">
<!ELEMENT alias (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT short (#PCDATA)>

<!ELEMENT data (#PCDATA)>
<!ATTLIST data name CDATA #REQUIRED>

<!ELEMENT call (#PCDATA)>
<!ELEMENT include (#PCDATA)>

<!ELEMENT func (call, desc, example?)>
<!ATTLIST func name CDATA #REQUIRED>

<!ELEMENT class (constructor, desc, example?, (attr | method)*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT constructor (#PCDATA)>

<!ELEMENT attr (desc, example?)>
<!ATTLIST attr name CDATA #REQUIRED>

<!ELEMENT method (call, desc, example*)>
<!ATTLIST method name CDATA #REQUIRED>

]>

=== pombreda/pgreloaded/doc/src/sdlkeyboard.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.keyboard">
  <short>SDL keyboard I/O wrapper module</short>
  <desc>SDL keyboard I/O wrapper module</desc>

  <func name="enable_repeat">
    <call>enable_repeat (delay, interval) -> None</call>
    <desc>
      Enables or disables the keyboard repeat rate.

      Enables or disables the keyboard repeat rate. *delay* specifies how
      long a key must be pressed before the repeat begins. *interval* is
      the speed with which it repeats. *delay* and *interval* are expressed
      as milliseconds. Thus, after the initial delay has passed,
      repeated :const:`KEYDOWN` events are sent through the event queue, using
      the specified *interval*.

      Setting *delay* to 0 will disable repeating completely.
    </desc>
  </func>
  <func name="enable_unicode">
    <call>enable_unicode ([enable]) -> bool</call>
    <desc>
      Enables or disables unicode input handling.

      Enables or disables unicode input handling. If the argument is
      omitted, the function will return the current unicode handling
      state.

      By default unicode handling is enabled and for keyboard events,
      the *unicode* member of the event will be filled with the
      corresponding unicode character.
    </desc>
  </func>
  <func name="get_key_name">
    <call>get_key_name (key) -> str</call>
    <desc>
      Get the descriptive name for a key constant.
    </desc>
  </func>
  <func name="get_mod_state">
    <call>get_mod_state () -> int</call>
    <desc>
      Returns the current state of the modifier keys (CTRL, ALT, etc.).

      Returns a single integer representing a bitmask of all the
      modifier keys being held. Using bitwise operators you can test if
      specific shift keys are pressed, the state of the capslock button,
      and more.

      The bitmask will consist of the various keyboard modifier flags as
      specified in the :mod:`pygame2.sdl.constants` module.
    </desc>
    <example>
      ...
      import pygame2.sdl.keyboard as keyboard
      import pygame2.sdl.constants as constants
      ...
      
      # Check, whether any control ar alt key was pressed.
      if (keyboard.get_mod_state () &amp; (constants.KMOD_CTRL | constants.KMOD_ALT)) != 0:
          print ("A control or alt key is pressed")
      ...
    </example>
  </func>
  <func name="get_repeat">
    <call>get_repeat () -> int, int</call>
    <desc>
      Gets the currently set keyboard repeat delay and interval.
    </desc>
  </func>
  <func name="get_state">
    <call>get_state () -> dict</call>
    <desc>
      Gets the current keyboard state.

      Gets a dictionary with the current keyboard state. The keys of the
      dictionary are the key constants, the boolean values of the
      dictionary indicate, whether a certain key is pressed or not.
    </desc>
  </func>
  <func name="set_mod_state">
    <call>set_mod_state (mod) -> None</call>
    <desc>
      Sets the current modifier key state.

      Sets the current modifier key state. mod has to be a bitwise OR'd
      combination of the keyboard modifier flags as specified in the
      :mod:`pygame2.sdl.constants` module.
    </desc>
    <example>
      ...
      import pygame2.sdl.keyboard as keyboard
      import pygame2.sdl.constants as constants
      ...
      
      # Enable numlock.
      keyboard.set_mod_state (constants.KMOD_NUM)
      ...
    </example>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlexttransform.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlext.transform">
  <short>SDL surface transformation algorithms</short>
  <desc>SDL surface transformation algorithms
  
    A surface transform is an operation that moves or resizes the pixels. All
    these functions take a surface to operate on and return a new surface with
    the results.

    Some of the transforms are considered destructive. This means every time
    they are performed they lose pixel data. Common examples of this are
    resizing and rotating. For this reason, it is better to retransform the
    original surface than to keep transforming an image multiple times.
    (For example, suppose you are animating a bouncing spring which expands and
    contracts. If you applied the size changes incrementally to the previous
    images, you would lose detail. Instead, always begin with the original
    image and scale to the desired size.)
  </desc>

  <func name="average_color">
    <call>average_color (surface[, rect]) -> Color</call>
    <desc>
      Finds the average color of a surface.
      
      Finds the average color of a :class:`pygame2.sdl.video.Surface` and
      returns it. The optional *rect* argument can be used to find the average
      color for a specific region on the :class:`pygame2.sdl.video.Surface`.
    </desc>
  </func>
  <func name="average_surfaces">
    <call>average_surfaces ((surface1, surface2, ...)[, destsurface]) -> Surface</call>
    <desc>
      Creates a new surface with the average colors from a list of surfaces.
      
      This finds the average color for each of the passed surfaces and creates
      a new :class:`pygame2.sdl.video.Surface` with those colors. If a
      destination surface is passed, it will be used instead of creating a new
      :class:`pygame2.sdl.video.Surface`.

      .. note::
      
        The destination surface must have the same size as the largest
        :class:`pygame2.sdl.video.Surface` of the passed list.
    </desc>
  </func>
  <func name="chop">
    <call>chop (surface, rect) -> Surface</call>
    <desc>
      Extracts a portion of a surface.

      Extracts a portion of a *surface*. All vertical and horizontal pixels
      surrounding the given rectangle area are removed. The corner areas
      (diagonal to the *rect*) are then brought together and the result will be
      returned as a new :class:`pygame2.sdl.video.Surface`

      .. note::
      
        If you want a "crop" that returns the part of an image within a
        rect, you can blit with a rect to a new surface.
    </desc>
  </func>
  <func name="flip">
    <call>flip (surface, flipx, flipy) -> Surface</call>
    <desc>
      Flips a surface horizontically, vertically or over both axes.
      
      This can flip a *surface* either vertically, horizontally, or both.
      Flipping a Surface is nondestructive and returns a new
      :class:`pygame2.sdl.video.Surface` with the same dimensions. 
    </desc>
  </func>
  <func name="get_filtertype">
    <call>get_filtertype () -> int</call>
    <desc>
      Gets the currently set filter type.
    </desc>
  </func>
  <func name="set_filtertype">
    <call>set_filtertype (type) -> int</call>
    <desc>
      Tries to apply a certain filter mechanism to use.
      
      Tries to apply a certain filter mechanism for the :func:`smoothscale`
      function. Depending on which architecture and how Pygame2 was built,
      not all available filters from :mod:`pygame2.sdlext.constants` might
      be supported. In case the passed *type* is not supported for the
      executing system, the filter type will be automatically set back to
      :const:`FILTER_C`.
      
      The return value will be the effective filter type used.
    </desc>
  </func>
  <func name="laplacian">
    <call>laplacian (surface[, destsurface]) -> Surface</call>
    <desc>
      Finds the edges in a surface using the laplacian algorithm.
      
      Finds the edges in a *surface* using the laplacian algorithm. If a
      destination surface is provided, it will be used for drawing the results
      instead of creating a new :class:`pygame2.sdl.video.Surface`.
      
      .. note::
        
        The destination surface must have the same size as the *surface* to
        find the edges in.
    </desc>
  </func>
  <func name="rotate">
    <call>rotate (surface, angle) -> Surface</call>
    <desc>
      Rotates a surface.
      
      Rotates a *surface* using the specified *angle* in degrees. For positive
      angles, the rotation will be counterclockwise, negative angles will cause
      a clockwise rotation. 
      
      Unless rotating by 90 degree increments, the *surface* will be padded
      larger to hold the new size. If the image has pixel alphas, the padded
      area will be transparent. Otherwise a color will picked that matches the
      surface colorkey or the topleft pixel value.
    </desc>
  </func>
  <func name="scale">
    <call>scale (surface, width, height[, destsurface]) -> Surface
      scale (surface, size[, destsurface]) -> Surface
    </call>
    <desc>
       Resizes the surface to a new resolution.

       This is a fast scale operation that does not sample the results. An
       optional destination surface can be used, rather than have it create a
       new one. This is faster if you want to repeatedly scale something.
       
       .. note:: 
         
         The destination surface must cover the size of the scaled result
         and feature the same format.
    </desc>
  </func>
  <func name="scale2x">
    <call>scale (surface[, destsurface]) -> Surface</call>
    <desc>
      Scales a surface to the double of its original size.
      
      This will return a new :class:`pygame2.sdl.video.Surface` that is double
      the size of the original. It uses the AdvanceMAME Scale2X algorithm which
      does a 'jaggie-less' scale of bitmap graphics.
      
      This really only has an effect on simple images with solid colors. On
      photographic and antialiased images it will look like a regular
      unfiltered scale. An optional destination surface can be used, rather
      than to have it create a new one. This is faster if you want to
      repeatedly scale something.

      .. note:: 
         
         The destination surface must be twice the size of the *surface*
         passed in and feature the same format.
    </desc>
  </func>
  <func name="smoothscale">
    <call>smoothscale (surface, width, height[, destsurface]) -> Surface
      smoothscale (surface, size[, destsurface]) -> Surface
    </call>
    <desc>
      Resizes the surface to a new resolution using smoothing algorithms.

      Uses one of two different algorithms for scaling each dimension of the
      input surface as required. For shrinkage, the output pixels are area
      averages of the colors they cover. For expansion, a bilinear filter is
      used.

      For AMD64 and i686 architectures, optimized MMX and SSE filter routines
      are included and will run much faster than other machine types. The filter
      routines can be get and set using :func:`get_filtertype` and
      :func:`set_filtertype`

      This function only works for 24-bit or 32-bit surfaces. An exception will
      be thrown if the input surface bit depth is less than 24.       

      .. note::
        
        The destination surface must cover the size of the scaled result
        and feature the same format.
    </desc>
  </func>
  <func name="threshold">
    <call>threshold (surface, color, threscolor[, destsurface]) -> Surface
      threshold (surface, colorsurface, threscolor[, destsurface]) -> Surface
    </call>
    <desc>TODO</desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlextscrap.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlext.scrap">
  <short>OS clipboard access for SDL</short>
  <desc></desc>

  <func name="contains">
    <call></call>
    <desc></desc>
  </func>
  <func name="get">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_mode">
    <call></call>
    <desc></desc>
  </func>
  <func name="get_types">
    <call></call>
    <desc></desc>
  </func>
  <func name="init">
    <call></call>
    <desc></desc>
  </func>
  <func name="lost">
    <call></call>
    <desc></desc>
  </func>
  <func name="put">
    <call></call>
    <desc></desc>
  </func>
  <func name="quit">
    <call></call>
    <desc></desc>
  </func>
  <func name="set_mode">
    <call></call>
    <desc></desc>
  </func>
  <func name="was_init">
    <call></call>
    <desc></desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlextdraw.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlext.draw">
  <short>extended SDL drawing methods</short>
  <desc>Extension module containing simple 2D drawing methods for the pygame2
    SDL modules. Several methods utilize code from the SDL_gfx library, and 
    were optimised and changed in several ways.
   </desc>

  <func name="aaline">
    <call>aaline (surface, color, x1, y1, x2, y2[, blend]) -> Rect
    aaline (surface, color, point1, point2[, blend]) -> Rect</call>
    <desc>Draws a fine anti-aliased line.
      
      Draws an anti-aliased line on a *surface*. If *blend* is True, the
      shades will be be blended with existing pixel shades instead of
      overwriting them.
      
      The returned :class:`pygame2.Rect` describes the area affected by
      the changes.
    </desc>
  </func>
  <func name="aalines">
    <call>aalines (surface, color, (point1, point2, ...) [, blend]) -> Rect
    </call>
    <desc>Draws multiple contiguous anti-aliased line segments on a surface.
    
      Draws a sequence of anti-aliased lines with a fixed width of 1px
      on a *surface*. If *blend* is True, the shades will be be blended
      with existing pixel shades instead of overwriting them.

      The returned :class:`pygame2.Rect` describes the area affected by
      the changes.
    </desc>
  </func>
  <func name="aapolygon">
    <call>aapolygon (surface, color, (point1, point2, ...) [, blend]) -> Rect
    </call>
    <desc>Draws an anti-aliased polygonal shape on a surface.
    
      Draws an polygonal shape on a *surface* with an fixed line width of
      1px. If *blend* is true, the shades will be be blended with existing
      pixel shades instead of overwriting them.
      
      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="arc">
    <call>arc (surface, color, rect, startangle, stopangle[, width]) -> Rect
    </call>
    <desc>Draws an elliptical arc on a surface.
    
      Draws an elliptical arc on a *surface* with an optionally
      specified line width. If the *width* argument is omitted, the line
      will be 1px thick. If *width* is set to 0, a filled shape will be
      drawn. The *startangle* and *stopangle* arguments are the initial
      and final angle in degrees.
      
      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="circle">
    <call>circle (surface, color, x, y, radius[, width]) -> Rect
    circle (surface, color, point, radius[, width]) -> Rect</call>
    <desc>Draws a circular shape on a surface.
    
      Draws a circular shape on a *surface* with an optionally specified
      line width. If the *width* argument is omitted, the line will be
      1px thick. If *width* is set to 0, a filled circular shape will be
      drawn. The *x*, *y* point denotes the center of the circle.
      
      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="ellipse">
    <call>ellipse (surface, color, rect[, width]) -> Rect</call>
    <desc>Draws an elliptical shape on a surface.
    
      Draws an elliptical shape on a *surface* with an optionally
      specified line width. If the *width* argument is omitted, the line
      will be 1px thick. If *width* is set to 0, a filled elliptical
      shape will be drawn. The passed :class:`pygame2.Rect` denotes the
      area, the elliptical shape will be drawn in.
      
      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="line">
    <call>line (surface, color, x1, y1, x2, y2[, width]) -> Rect
    line (surface, color, point1, point2[, width]) -> Rect</call>
    <desc>Draws a straight line segment on a surface.

      Draws a straight line segment on a *surface* with an optionally
      specified line width. If the *width* argument is omitted, the line
      will be 1px thick. There are no endcaps, the ends are squared off
      for thick lines.
      
      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="lines">
    <call>lines (surface, color, (point1, point2, ...) [, width]) -> Rect</call>
    <desc>Draws multiple contiguous line segments on a surface.
    
      Draws a sequence of lines on a *surface* with an optionally
      specified line width. If the *width* argument is omitted, the
      lines will be 1px thick.

      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="polygon">
    <call>polygon (surface, color, (point1, point2), ...) [, width]) -> Rect
    </call>
    <desc>Draws a polygonal shape on a surface.
    
      Draws a polygonal shape on a *surface* with an optionally
      specified line width. If the *width* argument is omitted, the line
      will be 1px thick. If *width* is set to 0, a filled polygon will
      be drawn.
      
      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
  <func name="rect">
    <call>rect (surface, color, rect [, width]) -> Rect</call>
    <desc>Draws a rectangular shape on a surface.
    
      Draws a rectangular shape on a *surface* with an optionally
      specified line width. If the *width* argument is omitted, the line
      will be 1px thick. If the *width* is set to 0, a filled
      rectangular shape will be drawn.

      The returned :class:`pygame2.Rect` describes the area affected by the
      changes.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlmouse.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.mouse">
  <short>SDL mouse I/O wrapper module</short>
  <desc>SDL mouse I/O wrapper module</desc>

  <class name="Cursor">
    <constructor>Cursor (data, mask, width, height[, hotx, hoty]) -> Cursor
    Cursor (data, mask, size[, point]) -> Cursor
    </constructor>
    <desc>
      Creates a new mouse cursor pointer.

      Creates a new mouse cursor pointer from the specified pixel *data*
      and pixel *mask*. The *mask* is used for applying transparency to the
      data defining the mouse cursor.
    </desc>
  </class>

  <func name="get_position">
    <call>get_position () -> x, y</call>
    <desc>
      Gets the current mouse position on the main screen.
    </desc>
  </func>
  <func name="get_rel_position">
    <call>get_rel_position () -> x, y</call>
    <desc>
      Gets the relative mouse movement.

      Gets the relative mouse movement since the last call to this function.
    </desc>
  </func>
  <func name="get_rel_state">
    <call>get_rel_state () -> buttons, x, y</call>
    <desc>
      Gets the relative mouse state.
      
      Gets the relative mouse state since the last call to this function.
    </desc>
  </func>
  <func name="get_state">
    <call>get_state () -> buttons, x, y</call>
    <desc>
      Gets the current mouse state.
      
      Gets the current mouse state. The returned buttons value
      represents a bitmask with the pressed buttons.
    </desc>
  </func>
  <func name="set_cursor">
    <call>set_cursor (cursor) -> None</call>
    <desc>
      Sets the mouse cursor to be shown.
    
      Sets the mouse cursor to be displayed. The change will be visible
      immediately.
    </desc>
  </func>
  <func name="set_position">
    <call>set_position (x, y) -> None
    set_position (point) -> None</call>
    <desc>
      Sets the position of the mouse cursor.
    
      Sets the position of the mouse cursor on the main screen. This
      behaves exactly as the :meth:`warp` method.
    </desc>
  </func>
  <func name="set_visible">
    <call>set_visible (show) -> state</call>
    <desc>
      Toggles whether the cursor is shown on the screen.
    
      Toggles whether the cursor is shown on the screen. This
      behaves exactly as the :meth:`show_cursor` method.
    </desc>
  </func>
  <func name="show_cursor">
    <call>show_cursor (show) -> state</call>
    <desc>
      Toggles whether the cursor is shown on the screen.
      
      Toggles whether the cursor is shown on the screen. *show* can be a
      boolean or one a value of :const:`ENABLE`, :const:`DISABLE` and
      :const:`QUERY`. :const:`QUERY` will not change the visibility state but
      query, if the cursor is currently shown or not.
      
      The state returned is a value of :const:`ENABLE` and :const:`DISABLE`,
      indicating, whether the cursor is currently shown or not.
    </desc>
  </func>
  <func name="warp">
    <call>warp (x, y) -> None
    warp (point) -> None</call>
    <desc>
      Sets the position of the mouse cursor.
    
      Sets the position of the mouse cursor on the main screen. This
      also will generate a mouse motion event.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlgl.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.gl">
  <short>SDL OpenGL access wrapper module</short>
  <desc>SDL OpenGL access wrapper module</desc>

  <func name="get_attribute">
    <call>get_attribute (attribute) -> int</call>
    <desc>
      Gets an OpenGL attribute value.
      
      Gets the current value of the specified OpenGL attribute constant.
    </desc>
  </func>
  <func name="get_proc_address">
    <call>get_proc_address (procname) -> CObject</call>
    <desc>
      Gets the proc address of a function in the loaded OpenGL libraries.
      
      The proc address is an encapsuled function pointer and as such only
      useful for ctypes bindings or other C API modules.
    </desc>
  </func>
  <func name="load_library">
    <call>load_library (libraryname) -> None</call>
    <desc>
      Loads the desired OpenGL library.
      
      Loads the desired OpenGL library specified by the passed full qualified
      path. This must be called before any first call to
      :meth:`pygame2.sdl.video.set_mode` to have any effect.
    </desc>
  </func>
  <func name="set_attribute">
    <call>set_attribute (attribute, value) -> None</call>
    <desc>
      Sets an OpenGL attribute value.
      
      Sets the value of the specified OpenGL attribute.
    </desc>
  </func>
  <func name="swap_buffers">
    <call>swap_buffers () -> None</call>
    <desc>Swap the OpenGL buffers, if double-buffering is supported.</desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlmixermusic.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlmixer.music">
  <short>SDL_mixer music playback</short>
  <desc>
    This module takes care of general music management and operations,
    which can apply to the currently set :class:`Music` object.
  </desc>

  <func name="fade_out">
    <call>fade_out (ms) -> None</call>
    <desc>Fades out the current music playback.
    
      This gradually reduces the volume for the current music to 0 over *ms*
      milliseconds. The music will be halted after the fadeout is complete.
    </desc>
  </func>
  <func name="fading">
    <call>fading () -> int</call>
    <desc>Gets the fading status of the music.</desc>
  </func>
  <func name="get_volume">
    <call>get_volume () -> int</call>
    <desc>Gets the volume of the music.</desc>
  </func>
  <func name="halt">
    <call>halt () -> None</call>
    <desc>Halts the music playback and resets its state.</desc>
  </func>
  <func name="pause">
    <call>pause () -> None</call>
    <desc>Pauses the music playback.</desc>
  </func>
  <func name="paused">
    <call>paused () -> bool</call>
    <desc>Gets, whether the music playback is currently paused.</desc>
  </func>
  <func name="playing">
    <call>playing () -> bool</call>
    <desc>Gets, whether the music is currently playing.</desc>
  </func>
  <func name="resume">
    <call>resume () -> None</call>
    <desc>Resumes the previously paused music playback</desc>
  </func>
  <func name="rewind">
    <call>rewind () -> None</call>
    <desc>Rewinds the music to the start.</desc>
  </func>
  <func name="set_position">
    <call>set_position (pos) -> None</call>
    <desc>Sets the current playback position.</desc>
  </func>
  <func name="set_volume">
    <call>set_volume (volume) -> int</call>
    <desc>Sets the volume for the music.
    
      Sets the volume for the music and returns the previous set volume.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlextfastevent.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlext.fastevent">
  <short>fast SDL event handling module</short>
  <desc>fast SDL event handling module</desc>

  <class name="Event">
    <constructor>Event (type, dict) -> Event</constructor>
    <desc>
      Creates a new event to be used in the event messaging system.

      This is exactly the same type as the
      :class:`pygame2.sdl.event.Event` class. Take a look at its
      documentation for more details.
    </desc>
    <attr name="name"><desc>Gets the name of the Event.</desc></attr>
    <attr name="type"><desc>Gets type id of the Event.</desc></attr>
  </class>

  <func name="get">
    <call>get () -> [Event, Event, ...]</call>
    <desc>
      Gets events from the event queue.

      Gets the current events from the event queue. If no argument is
      passed, all currently available events are received from the event
      queue and returned as list. Otherwise, the argument can be a
      sequence or a bitmask combination of event types to receive from
      the queue.

      If no matching events are found on the queue, an empty list will be
      returned.
    </desc>
  </func>
  <func name="init">
    <call>init () -> None</call>
    <desc>
      Initializes the underlying fastevents system.
    </desc>
  </func>
  <func name="poll">
    <call>poll () -> Event</call>
    <desc>
      Gets a single event from the event queue.

      Returns a single event from the queue. If the event queue is
      empty, None will be returned. If an event is available and
      returned, it will be removed from the queue.
    </desc>
  </func>
  <func name="push">
    <call>push (event) -> None</call>
    <desc>
      Places a new event at the end of the event queue.

      This is usually used for placing user defined events on the event
      queue. You also can push user created device events on the queue,
      but this will not change the state of the device itself.
    </desc>
  </func>
  <func name="quit">
    <call>quit () -> None</call>
    <desc>
      Quits the underlying fastevents system and releases all hold resources.
    </desc>
  </func>
  <func name="wait">
    <call>wait () -> Event</call>
    <desc>
      Waits indefinitely for the next available event.

      This is a blocking method, that only returns, if an event occurs
      on the event queue. Once an event occurs, it will be returned to
      the caller and removed from the queue. While the program is
      waiting it will sleep in an idle state.
    </desc>
  </func>
</module>
