=== pombreda/pgreloaded/doc/src/api.dtd
<!DOCTYPE module [
<!ELEMENT module
          (show?, alias?, short, desc, example?,
          (data | func | class)*, include*)
          >
<!ATTLIST module name CDATA #REQUIRED>

<!ELEMENT show (0 | 1) "1">
<!ELEMENT alias (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT short (#PCDATA)>

<!ELEMENT data (#PCDATA)>
<!ATTLIST data name CDATA #REQUIRED>

<!ELEMENT call (#PCDATA)>
<!ELEMENT include (#PCDATA)>

<!ELEMENT func (call, desc, example?)>
<!ATTLIST func name CDATA #REQUIRED>

<!ELEMENT class (constructor, desc, example?, (attr | method)*)>
<!ATTLIST class name CDATA #REQUIRED>

<!ELEMENT constructor (#PCDATA)>

<!ELEMENT attr (desc, example?)>
<!ATTLIST attr name CDATA #REQUIRED>

<!ELEMENT method (call, desc, example*)>
<!ATTLIST method name CDATA #REQUIRED>

]>

=== pombreda/pgreloaded/doc/src/sdlbase.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.base">
  <show>0</show>
  <alias>pygame2.sdl</alias>
  <short>basic SDL wrapper module</short>
  <desc>
    Basic Pygame2 SDL wrapper functions.
  </desc>

  <func name="get_compiled_version">
    <call>get_compiled_version () -> (int, int, int)</call>
    <desc>
      Gets the SDL version pygame2 was compiled against as three-value tuple.

      This version is built at compile time. It can be used to detect
      which features may not be available through Pygame, if it is used
      as precompiled package using a different version of the SDL
      library.
    </desc>
  </func>
  <func name="get_error">
    <call>get_error () -> str</call>
    <desc>
      Gets the last SDL error message occured.

      SDL maintains an internal error message. This message will usually
      be given to you when a :exc:`pygame2.Error` is raised.

      You will rarely need to call this function.
    </desc>
  </func>
  <func name="get_version">
    <call>get_version () -> (int, int, int)</call>
    <desc>
      Gets the SDL version pygame2 currently uses as three-value tuple.

      This version is detected at runtime. It can be used to detect
      which features may not be available through Pygame, if it is used
      as precompiled package using a different version of the SDL library.
    </desc>
  </func>
  <func name="init">
    <call>init (flags) -> bool</call>
    <desc>
      Initializes the underlying SDL library.

      Initializes the underlying SDL library using the passed SDL
      flags. The flags indicate, which subsystems of SDL should be
      initialized and can be a bitwise combination of the initialization
      constants of the :mod:`pygame2.sdl.constants` module.

      In case an error occured, False will be returned. The detailled
      error can be received using :func:`get_error`.
    </desc>
  </func>
  <func name="init_subsystem">
    <call>init_subsystem (flags) -> bool</call>
    <desc>
      Initializes one or more SDL subsystems.

      In case a specific part of SDL was not initialized using
      :func:`init`, this function can be used to initialize it at
      a later time.

      In contrast to the original SDL library, you do not need to call
      :func:`init` beforehand to initialize anything. In
      case it was not done before, :func:`init` will be
      called implicitly with the passed *flags*.

      .. note::
        
        Please be aware, that timers need a special treatment, which is not
        be met by using :data:`INIT_TIMER` alone. For more details, take a look
        at the :mod:`pygame2.sdl.time` module documentation.

      In case an error occured, False will be returned. The detailled
      error can be received using :func:`get_error`.
    </desc>
  </func>
  <func name="quit">
    <call>quit () -> None</call>
    <desc>
      Shuts down all subsystems of the underlying SDL library.

      After calling this function, you should not invoke any SDL related
      class, method or function as they are likely to fail or might give
      unpredictable results.
    
      .. note::
        
        Please be aware, that timers need a special treatment, which is not
        be met by using :data:`INIT_TIMER` alone. For more details, take a look
        at the :mod:`pygame2.sdl.time` module documentation.
    </desc>
  </func>
  <func name="quit_subsystem">
    <call>quit_subsystem (flags) -> None</call>
    <desc>
      Shuts down one or more subsystems of the underlying SDL library.

      After calling this function, you should not invoke any class,
      method or function related to the specified subsystems as they are
      likely to fail or might give unpredictable results.
    
      .. note::
        
        Please be aware, that timers need a special treatment, which is not
        be met by using :data:`INIT_TIMER` alone. For more details, take a look
        at the :mod:`pygame2.sdl.time` module documentation.
    </desc>
  </func>
  <func name="was_init">
    <call>was_init ([flags]) -> long</call>
    <desc>
      Gets a bitwise OR'ed combination of the initialized SDL subsystems.

      Returns a bitwise combination of the currently initialized SDL
      subsystems. If *flags* is passed, only the listed subsystems in
      *flags* will be passed and the initialized ones of those returned.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlextbase.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlext.base">
  <show>0</show>
  <alias>pygame2.sdlext</alias>
  <short>basic extensions for SDL modules</short>
  <desc>
    Basic extensions for the pygame2 SDL wrapper.
  </desc>

  <class name="PixelArray">
    <constructor>PixelArray (surface) -> PixelArray</constructor>
    <desc>
      Creates a new PixelArray from the specified
      :class:`pygame2.sdl.video.Surface`.

      The PixelArray wraps up a :class:`pygame2.sdl.video.Surface` and provides
      a direct 2D array access to its pixels using the surface's columns as
      first and its rows as second axis. It supports slicing and row and pixel
      manipluation while in place operations such as addition, subtraction,
      multiplication, division and so forth are not allowed.

      While it is possible to assign both, integer color values and RGB(A)
      color tuples, the PixelArray will only use integers for the
      color representation. Thus, checking for certain colors has to be done
      using the :meth:`pygame2.sdl.video.PixelFormat.map_rgba` method of the
      surface's :attr:`pygame2.sdl.video.Surface.format`,
      the PixelArray was created for. ::

        pxarray = pygame.PixelArray (surface)
        # Check, if the first pixel at the topleft corner is blue
        if pxarray[0][0] == surface.format.map_rgba ((0, 0, 255)):
            ...
      
      If you operate on a slice, you also can use arbitrary sequences or
      other PixelArray objects to modify the pixels. They have to match
      the size of the PixelArray however. ::

        pxarray[a:b] = 0xFF00FF                   # set all pixels to 0xFF00FF
        pxarray[a:b] = (0xFF00FF, 0xAACCEE, ... ) # first pixel = 0xFF00FF,
        # second pixel  = 0xAACCEE, ...
        pxarray[a:b] = ((255, 0, 255), (170, 204, 238), ...) # same as above
        pxarray[a:b] = ((255, 0, 255), 0xAACCEE, ...)        # same as above
        pxarray[a:b] = otherarray[x:y]            # slice sizes must match

      Note, that something like ::

        pxarray[2:4][3:5] = ...

      will not cause a rectangular manipulation. Instead it will be
      first sliced to a two-column array, which then shall be sliced by
      columns once more, which will fail due an IndexError. This is
      caused by the slicing mechanisms in python and an absolutely
      correct behavior. Create a single columned slice first, which you
      can manipulate then: ::

        pxarray[2][3:5] = ...
        pxarray[3][3:5] = ...

      If you want to make a rectangular manipulation or create a view of
      a part of the PixelArray, you also can use the subscript
      abilities. You can easily create different views by creating
      'subarrays' using the subscripts. ::

        # Create some new PixelArray objects providing a different view
        # of the original array/surface.
        newarray = pxarray[2:4,3:5]
        otherarray = pxarray[::2,::2]

      Subscripts also can be used to do fast rectangular pixel
      manipulations instead of iterating over the x or y axis as above. ::

        pxarray[::2,:] = (0, 0, 0)                # Make each second column black.

      During its lifetime, the PixelArray locks the surface, thus you
      explicitly have to delete it once it is not used anymore and the
      surface should perform operations in the same scope.
    </desc>
    <method name="compare">
      <call>compare (array, distance=0, weights=(0.299, 0.587, 0.114)) -> PixelArray</call>
      <desc>
        Compares the PixelArray with another one.

        Compares the contents of the PixelArray with those from the
        passed PixelArray. It returns a new PixelArray with a
        black/white color mask that indicates the differences (white) of
        both arrays. Both PixelArray objects must have indentical bit
        depths and dimensions.

        It uses a simple weighted euclidian distance formula to
        calculate the distance between the colors. The *distance* space
        ranges from 0.0 to 1.0 and is used as threshold for the color
        detection. This causes the comparision to mark pixels with a
        similar, but not exactly identical color, as black.
      </desc>
    </method>
    <method name="extract">
      <call>extract (color, distance=0, weights=(0.299, 0.587, 0.114)) -> PixelArray</call>
      <desc>
        Extracts the passed color from the PixelArray.

        Extracts the passed *color* by changing all matching pixels to
        white, while non-matching pixels are changed to black. This
        returns a new PixelArray with the black/white color mask.

        It uses a simple weighted euclidian distance formula to calculate
        the distance between the colors. The *distance* space ranges from
        0.0 to 1.0 and is used as threshold for the color detection.
        This causes the extraction to take pixels with a similar, but
        not exactly identical color, into account as well.
      </desc>
    </method>
    <method name="make_surface">
      <call>make_surface () -> :class:`pygame2.sdl.video.Surface`</call>
      <desc>
        Creates a new :class:`pygame2.sdl.video.Surface` from the current
        PixelArray.

        Creates a new :class:`pygame2.sdl.video.Surface` from the current
        PixelArray. Depending on the current PixelArray the size, pixel order
        etc. will be different from the original
        :class:`pygame2.sdl.video.Surface`. ::

          # Create a new surface flipped around the vertical axis.
          sf = pxarray[:,::-1].make_surface ()
      </desc>
    </method>
    <method name="replace">
      <call>replace (color, repcolor, distance=0, weights=(0.299, 0.587, 0.114)) -> None</call>
      <desc>
        Replaces the passed color in the PixelArray with another one.

        Replaces the pixels with the passed *color* in the PixelArray
        by changing them them to the passed replacement color.

        It uses a simple weighted euclidian distance formula to calculate
        the distance between the colors. The *distance* space ranges from 0.0
        to 1.0 and is used as threshold for the color detection. This
        causes the replacement to take pixels with a similar, but not
        exactly identical color, into account as well.

        This is an in place operation that directly affects the pixels
        of the PixelArray.
      </desc>
    </method>
    <attr name="surface">
      <desc>Gets the :class:`pygame2.sdl.video.Surface` the PixelArray uses.</desc>
    </attr>
  </class>

</module>

=== pombreda/pgreloaded/doc/src/sdltime.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdl.time">
  <short>SDL time handling and measurement wrapper module</short>
  <desc>SDL time handling and measurement wrapper module.
  </desc>

  <func name="add_timer">
    <call>add_timer (interval, callable[, data]) -> CObject</call>
    <desc>
      Adds a timer callback to be called periodically.
      
      Adds a timer callback to be called periodically using the specified
      *interval*. *callable* can be any callable objet, method or function.
      On invocation, the optional *data* will be passed to the callable. If
      *data* is a sequence, each item of it will be passed as single argument
      to the callable.
            
      This will return an CObject that acts as unique id for the timer callback.

      .. note::
      
        Timer callbacks will be invoked from a seperate thread, if the
        underlying SDL library can use threads. In those cases, the
        invoked callback will lock the interpreter instance, execute and
        release the lock. This in turn means that your callback must
        take care of not locking itself in order to wait for another
        function or thread to be executed within the same interpreter
        instance. Otherwise you can run into a classic dead lock
        situation.

        Any added timer will be removed automatically on calling :func:`quit`.
    </desc>
  </func>
  <func name="delay">
    <call>delay (time) -> None</call>
    <desc>
      Delays the execution for a specific time.
      
      Delays the program execution for a specific *time*. The *time* is
      expressed in milliseconds.

      .. note::

        This does *not* require :func:`init` to be called before.
    </desc>
  </func>
  <func name="get_ticks">
    <call>get_ticks () -> long</call>
    <desc>
      Gets the number of milliseconds since the initialization of the underlying
      SDL library.
      
      Gets the number of milliseconds since the initialization of the underlying
      SDL library. The value will wrap if the program runs for more than ~49
      days.
    </desc>
  </func>
  <func name="init">
    <call>init () -> None</call>
    <desc>
      Initializes the timer subsystem of the SDL library.
    </desc>
  </func>
  <func name="quit">
    <call>quit () -> None</call>
    <desc>
      Shuts down the timer subsystem of the SDL library.

      After calling this function, you should not invoke any class,
      method or function related to the timer subsystem as they are
      likely to fail or might give unpredictable results.
      
      .. note::
      
        Any timer set by :func:`set_timer` or :func:`add_timer` will be removed
        automatically on calling :func:`quit`.
    </desc>
  </func>
  <func name="remove_timer">
    <call>remove_timer (timerobj) -> None</call>
    <desc>
      Removes a previously added timer callback.
      
      Removes a previously added timer callback and throws an exception, if the
      passed object is not a matching timer object.
    </desc>
  </func>
  <func name="was_init">
    <call>was_init () -> bool</call>
    <desc>
      Returns, whether the timer subsystem of the SDL library is initialized.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlmixerchannel.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlmixer.channel">
  <short>SDL_mixer sound channel handling</short>
  <desc>
    This module takes care of general sound channel management and operations,
    which can apply to one or multiple channels at once without having a 
    concrete :class:`Channel` object around.
  </desc>

  <func name="allocate">
    <call>allocate (amount) -> (Channel, Channel, ...)</call>
    <desc>(Pre-)Allocates a set of Channel objects.
    </desc>
  </func>
  <func name="expire">
    <call>expire (ms) -> None</call>
    <desc>Halts the playback of all channels after *ms* milliseconds.</desc>
  </func>
  <func name="fade_out">
    <call>fade_out (ms) -> int</call>
    <desc>Fades out the current audio playback for all channels.
    
      This gradually reduces the volume for all channels to 0 over *ms*
      milliseconds. The channels will be halted after the fadeout is complete.
      
      The number of channels set to fade out will be returned.
    </desc>
  </func>
  <func name="get_volume">
    <call>get_volume () -> int</call>
    <desc>Gets the currently set overall volume for all Channel objects.</desc>
  </func>
  <func name="halt">
    <call>halt () -> None</call>
    <desc>Stops the sound playback for all Channel objects.</desc>
  </func>
  <func name="opened">
    <call>opened () -> int</call>
    <desc>Gets the number of currently open (allocated) channels.</desc>
  </func>
  <func name="pause">
    <call>pause () -> None</call>
    <desc>Pauses the sound playback for all Channel objects.</desc>
  </func>
  <func name="paused">
    <call>paused () -> int</call>
    <desc>Gets the number of channels being currently paused.</desc>
  </func>
  <func name="playing">
    <call>playing () -> int</call>
    <desc>Gets the number of channels currently playing.</desc>
  </func>
  <func name="resume">
    <call>resume () -> None</call>
    <desc>Resumes the playback for all paused Channel objects.</desc>
  </func>
  <func name="set_volume">
    <call>set_volume (volume) -> int</call>
    <desc>Sets the overall volume for all available Channel objects.

      Sets the volume for all available Channel objects and returns the previous
      set volume.
    </desc>
  </func>
</module>

=== pombreda/pgreloaded/doc/src/sdlmixerbase.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "api.dtd">

<module name="pygame2.sdlmixer.base">
  <show>0</show>
  <alias>pygame2.sdlmixer</alias>
  <short>basic SDL_mixer wrapper module</short>
  <desc>
    .. note::
      
      Do not use :mod:`pygame2.sdlmixer` and :mod:`pygame2.sdl.audio` at the
      same time. As they both deal with audio hardware access, this can lead
      to problems and weird behaviour.
  
  </desc>

  <class name="Channel">
    <constructor>Channel ([index]) -> Channel</constructor>
    <desc>Creates a new Channel for playing audio data
    
      Channel represents a playback destination for audio data.
      SDL_mixer can handle multiple channels to play audio simultanously.

      If *index* is omitted or smaller than 1, a new Channel will be created.
      Otherwise Channel will refer to an existing channel and reuse it.
      
      .. note::
         
         The state of an existing channel will not be reset.
    </desc>
    <attr name="chunk">
      <desc>The current :class:`Chunk` of audio data to be played.</desc>
    </attr>
    <method name="expire">
      <call>expire (ms) -> None</call>
      <desc>Halts the playback of the Channel after *ms* milliseconds.</desc>
    </method>
    <method name="fade_in">
      <call>fade_in (sound, ms[, loops, ticks]) -> None</call>
      <desc>Fades in the passed sound.
      
        This starts playing the passed *sound* at volume 0, which fades up to
        the maximum value over *ms* milliseconds. The *sound* will be played
        for *loops* + 1 number of times.
        
        *ticks* is the optional maximum time in milliseconds to stop playing
        after.
      </desc>
    </method>
    <method name="fade_out">
      <call>fade_out (ms) -> None</call>
      <desc>Fades out the current audio playback.
      
      This gradually reduces the volume to 0 over *ms* milliseconds. The channel
      will be halted after the fadeout is complete.
      </desc>
    </method>
    <attr name="fading">
      <desc>The fading status of the Channel.</desc>
    </attr>
    <method name="halt">
      <call>halt () -> None</call>
      <desc>Stops the audio playback immediately and resets the playback state
      </desc>
    </method>
    <method name="pause">
      <call>pause () -> None</call>
      <desc>Pauses the current audio playback.</desc>
    </method>
    <attr name="paused">
      <desc>Gets, whether the Channel playback is currently paused.</desc>
    </attr>
    <method name="play">
      <call>play (sound[, loops, ticks]) -> None</call>
      <desc>Starts the playback of an audio :class:`Chunk`.
      
        The audio chunk will be played for *loops* + 1 times (or one time only, 
        if *loops* is omitted).
        
        *ticks* is the optional maximum time in milliseconds to stop playing
        after.
      </desc>
    </method>
    <attr name="playing">
      <desc>Gets, whether the Channel is currently playing audio.</desc>
    </attr>
    <method name="resume">
      <call>resume () -> None</call>
      <desc>Resumes the playback of a paused sound chunk.</desc>
    </method>
    <attr name="volume">
      <desc>Gets or sets the channel volume.</desc>
    </attr>
  </class>

  <class name="Chunk">
    <constructor>Chunk (file) -> Chunk</constructor>
    <desc>Creates a new sound chunk for audio playback.
    
      .. note::

        The file object *must* support binary read and write
        access. This is especially important for Python 3.x users.
    </desc>
    <attr name="buf">
      <desc>Gets the raw audio buffer of the Chunk.</desc>
    </attr>
    <attr name="len">
      <desc>Gets the length of the audio data.</desc>
    </attr>
    <attr name="volume">
      <desc>Gets or sets the default volume for the audio data.</desc>
    </attr>
  </class>

  <class name="Music">
    <constructor>Music (file) -> Music</constructor>
    <desc>Creates a new sound chunk for music playback.

      .. note::

        The file object *must* support binary read and write
        access. This is especially important for Python 3.x users.
    </desc>
    <method name="fade_in">
      <call>fade_in (ms[, loops, pos]) -> None</call>
      <desc>Fades in the Music.
      
        This starts playing the Music at volume 0, which fades up to
        the maximum value over *ms* milliseconds. The Music will be played
        for *loops* + 1 number of times.
        
        *pos* is the position to start the playback from.
      </desc>
    </method>
    <method name="play">
      <call>play ([loops]) -> None</call>
      <desc>Starts the playback of the Music.
      
        Starts the playback of the Music. The music will be played once, if
        *loops* is omitted, otherwise it will be played *loops* + 1 times.
      </desc>
    </method>
    <attr name="type">
      <desc>Gets the music format.</desc>
    </attr>
  </class>

  <func name="close_audio">
    <call>close_audio () -> None</call>
    <desc>
      Closes an opened instance of the audio hardware.

      Use :func:`query_spec` to detect how often :func:`close_audio` has
      to be called.

      After calling this function (often enough), you should not invoke
      any SDL_mixer related class, method or function as they are likely
      to fail or might give unpredictable results.
    </desc>
  </func>
  <func name="get_compiled_version">
    <call>get_compiled_version () -> (int, int, int)</call>
    <desc>
      Gets the SDL_mixer version pygame2 was compiled against as three-value tuple.

      This version is built at compile time. It can be used to detect
      which features may not be available through Pygame, if it is used
      as precompiled package using a different version of the SDL_mixer
      library.
    </desc>
  </func>
  <func name="get_error">
    <call>get_error () -> str</call>
    <desc>
      Gets the last SDL_mixer error message occured.

      SDL_mixer maintains an internal error message. This message will
      usually be given to you when a :exc:`pygame2.Error` is raised.

      You will rarely need to call this function.
    </desc>
  </func>
  <func name="get_version">
    <call>get_version () -> (int, int, int)</call>
    <desc>
      Gets the SDL_mixer version pygame2 currently uses as three-value tuple.

      This version is detected at runtime. It can be used to detect
      which features may not be available through Pygame, if it is used
      as precompiled package using a different version of the SDL_mixer
      library.
    </desc>
  </func>
  <func name="init">
    <call>init ([flags]) -> int</call>
    <desc>
      Initializes the underlying SDL_mixer library.

      Initializes the underlying SDL_mixer library using the passed
      mixer flags. The flags indicate, which music library (FLAC, OGG,
      ...) SDL_mixer should initialize and can be a bitwise
      combination of the initialization constants of the
      :mod:`pygame2.sdlmixer.constants` module.

      In case an error occured, an exception will be raised.
    </desc>
  </func>
  <func name="open_audio">
    <call>open_audio (frequency, format, channels, chunksize) -> None</call>
    <desc>
      Initializes the mixer API and prepares the audio hardware for access.

      This must be called before using any other method or class for
      audio output. It initializes the API with a certain *frequency*
      (e.g. 44100 for 44.1 KHz).

      *format* is the sample format that will be used in the
      :class:`Chunk` and :class:`Music` objects and can be one of the
      :data:`AUDIO_XXX` constants.

      *channels* denotes the number of output channels, not the number
      of :class:`Channel` instances and can be 1 for mono or 2 for
      stereo sound.

      *chunksize* is the size of bytes used per output sample to
      stream. The larger the value, the more often the output hooks will
      be called. A good value for chunksize is between 1024 and 4096 on
      most computers (1kB - 4 kB).

      .. note::
      
        You can call this method multiple times with different
        values. In turn, you have to call :func:`close_audio` as often
        as you called :func:`open_audio` to shut anything down.
    </desc>
    <example>
      import pygame2.sdlmixer as mixer
      import pygame2.sdlmixer.constants as mixconst
      ...
      
      mixer.open_audio (22050, mixconst.AUDIO_U16SYS, 2, 2048)
    </example>
  </func>
  <func name="query_spec">
    <call>query_spec () -> (int, int, int, int)</call>
    <desc>
      Queries the actual settings used by the audio device.

      Queries the actual settings used by the audio device and returns
      the setting in the following order:

        * number of times :func:`open_audio` was called
        * current frequency
        * current format
        * current channel setting (stereo or mono)

     See :func:`open_audio` for the typical meaning and values of the
     returned tuple.
    </desc>
  </func>
  <func name="quit">
    <call>quit () -> None</call>
    <desc>
      Shuts down the underlying SDL_mixer library.

      After calling this function, you should not invoke any SDL_mixer
      related class, method or function as they are likely to fail or
      might give unpredictable results.
    </desc>
  </func>
  <func name="was_init">
    <call>was_init () -> bool</call>
    <desc>
      Gets, whether the SDL_mixer library was initialized or not.

      .. note::

         This only checks, whether the **SDL** flag :data:`INIT_AUDIO`
         was set.
    </desc>
  </func>
</module>
